import { Route } from '@angular/router';
import { HomeComponent } from './components/home.component';
import { ExamModeComponent } from './components/exam-mode/exam-mode.component';
import { SessionSummaryComponent } from './components/session-summary/session-summary.component';
import { PracticeModeSelectorComponent } from './components/practice-mode/selectors/practice-mode-selector.component';
import { PracticeModeComponent } from './components/practice-mode/exercises-container/practice-mode.component';
import { MaterialOrganizerComponent } from './components/organize-material/material-organizer.component';
import { FolderCreatorComponent } from './components/organize-material/creators/folder-creator/folder-creator.component';
import { FolderDetailsViewerComponent } from './components/organize-material/details-viewers/folder-details-viewer/folder-details-viewer.component';
import { LessonCreatorComponent } from './components/organize-material/creators/lesson-creator/lesson-creator.component';
import { LessonDetailsViewerComponent } from './components/organize-material/details-viewers/lesson-details-viewer/lesson-details-viewer.component';
import { FlashcardCreatorStandaloneComponent } from './components/organize-material/creators/flashcard-creator/standalone/flashcard-creator-standalone.component';
import { RegisterComponent } from './features/auth/register/RegisterComponent.component';
import { LandingPageComponent } from './components/landing-page.component';
import { DemoModeComponent } from './components/demo-mode/demo-mode.component';
import { LoginComponent } from './features/auth/login/login.component';
import { StudyMaterialManagerComponent } from './components/learning-resources-manager/deprecated/study-material-manager/study-material-manager.component';

export const appRoutes: Route[] = [
    { path: '', component: HomeComponent },
    { path: 'home', component: HomeComponent },
    { path: 'practice-selector', component: PracticeModeSelectorComponent },
    { path: 'exam', component: ExamModeComponent },
    { path: 'browse-lessons', component: MaterialOrganizerComponent },
    { path: 'session-summary', component: SessionSummaryComponent },
    { path: 'practice', component: PracticeModeComponent },
    { path: 'folder-creator', component: FolderCreatorComponent },
    { path: 'folder-details/:id', component: FolderDetailsViewerComponent },
    { path: 'lesson-creator/:id', component: LessonCreatorComponent },
    { path: 'lesson-creator', component: LessonCreatorComponent },
    { path: 'lesson-details/:id', component: LessonDetailsViewerComponent },
    { path: 'flashcard-creator', component: FlashcardCreatorStandaloneComponent },
    { path: 'register', component: RegisterComponent },
    { path: 'login', component: LoginComponent },
    { path: 'landing-page', component: LandingPageComponent },
    { path: 'demo-mode', component: DemoModeComponent },
    { path: 'manage-study-material', component: StudyMaterialManagerComponent },
];
