import { Route } from '@angular/router';
import { HomeComponent } from './features/home/home.component';
import { SessionSummaryComponent } from './features/session-summary/session-summary.component';
import { PracticeModeComponent } from './features/training-modes/practice/exercises-manager/practice-mode.component';
import { LessonCreatorComponent } from './features/resources-manager/lesson/lesson-creator/lesson-creator.component';
import { LessonDetailsViewerComponent } from './features/resources-manager/lesson/lesson-details/lesson-details-viewer.component';
import { FlashcardCreatorStandaloneComponent } from './components/organize-material/creators/flashcard-creator/standalone/flashcard-creator-standalone.component';
import { RegisterComponent } from './features/auth/register/RegisterComponent.component';
import { LandingPageComponent } from './features/landing/landing-page.component';
import { LoginComponent } from './features/auth/login/login.component';
import { PracticeModeSelectorComponent } from './features/training-modes/practice/main-controller/practice-mode-selector.component';
import { FolderCreatorComponent } from './features/resources-manager/folder/folder-creator/folder-creator.component';
import { FoldersViewerComponent } from './features/resources-manager/folder/folders-viewer/folders-viewer';
import { LessonsByFolderComponent } from './features/resources-manager/lesson/lessons-by-folder/lessons-by-folder.component';
import { SessionSummaryExamComponent } from './features/session-summary/session-summary-exam.component';

export const appRoutes: Route[] = [
    { path: '', component: HomeComponent },
    { path: 'home', component: HomeComponent },
    { path: 'practice-selector/:folderId', component: PracticeModeSelectorComponent },
    { path: 'session-summary', component: SessionSummaryComponent },
    { path: 'session-summary/exam', component: SessionSummaryExamComponent },
    { path: 'practice', component: PracticeModeComponent },
    { path: 'folder-creator', component: FolderCreatorComponent },
    { path: 'lessons-by-folder/:id', component: LessonsByFolderComponent },
    { path: 'lesson-creator/:id', component: LessonCreatorComponent },
    { path: 'lesson-creator', component: LessonCreatorComponent },
    { path: 'lesson-details/:id', component: LessonDetailsViewerComponent },
    { path: 'flashcard-creator', component: FlashcardCreatorStandaloneComponent },
    { path: 'register', component: RegisterComponent },
    { path: 'login', component: LoginComponent },
    { path: 'landing-page', component: LandingPageComponent },
    { path: 'manage-learning-resources', component: FoldersViewerComponent },
];
